silverblue-images: add bootc linting to all images to ensure best practices are being used.

diff --git a/silverblue-base/Containerfile b/silverblue-base/Containerfile
--- a/silverblue-base/Containerfile
+++ b/silverblue-base/Containerfile
@@ -65,3 +65,19 @@ ADD files/profile.d/vim-default-editor.sh /etc/profile.d/vim-default-editor.sh
 
 # Enable git prompt
 ADD files/profile.d/git-prompt.sh /etc/profile.d/git-prompt.sh
+
+# Cleanup image for linting
+RUN test -f /usr/lib/sysusers.d/qemu.conf || echo -e 'g qemu 107\nu qemu 107 "qemu user" / /usr/sbin/nologin' > /usr/lib/sysusers.d/qemu.conf && \
+    test -f /usr/lib/sysusers.d/libvirt.conf || echo -e 'g libvirt 963' > /usr/lib/sysusers.d/libvirt.conf && \
+    test -f /usr/lib/sysusers.d/screen.conf || echo -e 'g screen 84' > /usr/lib/sysusers.d/screen.conf
+
+RUN dnf remove -y glusterfs && \
+    sed -i '/gluster/d' /etc/passwd && \
+    sed -i '/gluster/d' /etc/group && \
+    sed -i '/gluster/d' /etc/passwd && \
+    sed -i '/gluster/d' /etc/group && \
+    rm -rf /var && mkdir /var && \
+    rm -rf /boot && mkdir /boot
+
+# Verify image is good
+RUN bootc container lint --fatal-warnings --skip baseimage-composefs
diff --git a/silverblue-shuttle-sz170r8v2/Containerfile b/silverblue-shuttle-sz170r8v2/Containerfile
--- a/silverblue-shuttle-sz170r8v2/Containerfile
+++ b/silverblue-shuttle-sz170r8v2/Containerfile
@@ -9,3 +9,12 @@ RUN dnf install -y akmod-nvidia xorg-x11-drv-nvidia-cuda nvtop glmark2 && \
 # Create nvidia akmods
 RUN install-nvidia-akmod.sh && \
     rm -rf /var /usr/bin/install-nvidia-akmod.sh
+
+# Cleanup image for linting
+RUN test -f /usr/lib/sysusers.d/akmods.conf || echo -e 'g akmods 963\nu akmods 992 "User is used by akmods to build akmod packages" /var/cache/akmods /sbin/nologin' > /usr/lib/sysusers.d/akmods.conf
+
+RUN rm -rf /var && mkdir /var && \
+    rm -rf /boot && mkdir /boot
+
+# Verify image is good
+RUN bootc container lint --fatal-warnings --skip baseimage-composefs
